EXPERIMENT:
  NAME: "hard_sample_s"
  TAG: "kd,resnet32x4,resnet8x4,2,9"
  PROJECT: "cifar100_baselines"
  LOGIT_STAND: True
DISTILLER:
  TYPE: "KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  LOSS:
    CE_WEIGHT: 0.1
    KD_WEIGHT: 9
    HARD_RATIO: 0.3
    EASY_WEIGHT: 1.0
    HARD_WEIGHT: 2.0
  TEMPERATURE: 2


